version: '3.8'

services:
  app:
    build: .
    container_name: fiber-jwt-app
    image: fiber-jwt-app-6
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
